name: bsc_mine_hub
description: SPARK Miner Pro
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  share_plus: ^8.0.2
  google_mobile_ads: ^4.0.0
