name: bsc_mine_hub
description: BSC Mine Hub Pro - Binance Smart Chain Mining App
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
